siscobros/siscobros/apps/main/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('siscobros.apps.main.views',
                       url(r'^index/', 'main_view', name="vista_principal"),
                       url(r'^ciudadela/$','CiudadelaView'),
                       url(r'^ciudadela/read/$', 'serializaCiudadela', name="ConsumeCiudadela"),
                       url(r'^ciudadela/add/$','InsertCiudadela',name='RegistraCiudadela'),
                       url(r'^ciudadela/edit/(\d+)$','UpdateCiudadela'),
                       url(r'^ciudadela/del/(\d+)$','EliminaCiudadela'),
                       url(r'^costovario/$','TransCostoVario', name='TransCostoVario'),
                       url(r'^costovario/cbo/$','ComboTipoAjax',name="ComboTipo"),
                       url(r'^costovario/read/$','serializaTrans', name='ConsumeTrans'),
                       url(r'^aseguradora/$','AseguradoraView'),
                       url(r'^aseguradora/read/$','serializaAseguradora'),
                       url(r'^aseguradora/add/$','InsertAseguradora'),
                       url(r'^aseguradora/edit/(\d+)$','UpdateAseguradora'),
                       url(r'^aseguradora/del/(\d+)$','EliminaAseguradora'),
                       url(r'^reportes/costovario/$','rptcostoview'),
                       url(r'^reportes/costovario/file/$','reportecosto'),
                       )

siscobros/siscobros/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'siscobros.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('siscobros.apps.main.urls')),
    url(r'^$', 'django.contrib.auth.views.login',{ 'template_name': 'main/login.html'}, name="login"),
    url(r'^logout/', 'django.contrib.auth.views.logout_then_login', name="logout"),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

siscobros/siscobros/apps/main/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
# Create your models here. http://www.tangowithdjango.com/book
#Mantenimiento de Aseguradora v
class Aseguradora(models.Model):
    #Id= models.AutoField(db_column="ASE_Id", primary_key=True, unique=True, null=False)
    Descripcion= models.CharField(db_column="ASE_Desc", max_length=45, verbose_name="Descripción")
    Usuario= models.CharField(max_length=30, db_column="ASE_Usua")
    Fecha= models.DateTimeField(db_column="ASE_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Descripcion',)
        db_table = 'SISCBR_MAseguradora'

#Mantenimiento de Bombero v
class Bombero(models.Model):
    #Id= models.AutoField(db_column="PER_Id", primary_key=True, unique=True, null=False)
    Ruc = models.CharField(db_column="BOM_Ruc", max_length=15, primary_key=True, null=False, unique=True)
    Nombre = models.CharField(db_column="BOM_Nombre", max_length=45)
    Logotipo = models.CharField(db_column="BOM_Logotipo", max_length=45)
    Direccion = models.CharField(db_column="BOM_Direccion", max_length= 45, verbose_name="Dirección")
    Telefono = models.CharField(db_column="BOM_Telefono", max_length= 45, verbose_name="Teléfono")
    Fax = models.CharField(db_column="BOM_Fax", max_length=20)
    Mail = models.EmailField(db_column="BOM_Mail", max_length=45, verbose_name="Email")
    Web = models.URLField(db_column="BOM_Web")
    Slogan = models.CharField(db_column= "BOM_Slogan", max_length=45)
    RUC_Comandante = models.CharField(db_column="BOM_Ruc_Comandante", max_length=15, null=False, unique=True,
                                            verbose_name="Ruc Comandante")
    Comandante = models.CharField(db_column="BOM_Comandante", max_length=45)
    Usuario = models.CharField(max_length=30, db_column= "BOM_Usua")
    Fecha = models.DateTimeField(db_column= "BOM_Fech", default=datetime.today(), verbose_name="Fecha de Creación")
    Cost_Titulo= models.DecimalField(db_column="BOM_Cost_Titulo", max_digits=10, decimal_places=2,
                                     verbose_name="Costo Título")
    Tasa_Predio = models.DecimalField(db_column="BOM_Tasa_Predio", max_digits=10, decimal_places=2,
                                     verbose_name="Tasa Predio")
    Tasa_Certificado = models.DecimalField(db_column="BOM_Tasa_Certificado", max_digits=10, decimal_places=2,
                                     verbose_name="Tasa Certificado")

    def __unicode__(self):
        return str(self.Nombre)

    class Meta:
        ordering = ('Nombre',)
        db_table = 'SISCBR_Bombero'

#Mantenimiento de Ciudadela
class Ciudadela(models.Model):
    #Id= models.AutoField(db_column="CIU_Id", primary_key=True, unique=True, null=False)
    Descripcion = models.CharField(db_column="CIU_Desc", max_length=45, verbose_name="Descripción")
    Usuario = models.CharField(max_length=30, db_column="CIU_Usua")
    Fecha= models.DateTimeField(db_column="CIU_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering= ('Descripcion',)
        db_table= 'SISCBR_MCiudadela'

#Mantenimiento de Cliente
class Cliente(models.Model):
    #Id= models.AutoField(db_column="CLI_Id", primary_key=True, unique=True, null=False)
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Cedula= models.CharField(db_column="CLI_Cedu", max_length=13, verbose_name="Cédula")
    Apellido= models.CharField(db_column="CLI_Apel", max_length=45)
    Nombre= models.CharField(db_column="CLI_Nomb", max_length=45)
    Direccion= models.CharField(db_column="CLI_Dire", max_length=45, verbose_name="Dirección")
    Telefono= models.CharField(db_column="CLI_Fono", max_length=20, verbose_name="Teléfono")
    Email= models.EmailField(db_column="CLI_Mail", max_length=45)
    Usuario= models.CharField(max_length=30, db_column="CLI_Usua")
    Fecha= models.DateTimeField(db_column="CLI_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return '%s %s'%(self.Nombre, self.Apellido)

    class Meta:
        ordering = ('Apellido',)
        db_table = 'SISCBR_MCliente'

#Local
class Local(models.Model):
    #Id= models.AutoField(db_column="LOC_Id", primary_key=True, unique=True, null=False)
    Cliente= models.ForeignKey(Cliente, db_column="CLI_Id")
    Aseguradora= models.ForeignKey(Aseguradora, db_column="ASE_Id")
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Descripcion= models.CharField(db_column="LOC_Desc", max_length=45, verbose_name="Descripción")
    Ruc= models.CharField(db_column="LOC_Ruc", max_length=13)
    Direccion= models.CharField(db_column="LOC_Direc", max_length=45, verbose_name="Dirección")
    Catastro= models.CharField(db_column="LOC_Cata", max_length=20)
    Telefono= models.CharField(db_column="LOC_Fono", max_length=20, verbose_name="Teléfono")
    Avaluo= models.DecimalField(db_column="LOC_Avaluo", max_digits=18, decimal_places=2, default=0.0)
    Poliza= models.CharField(db_column="LOC_NPol", max_length=20, verbose_name="N° de Póliza")
    Estado = models.BooleanField(db_column="LOC_Est", default=True)
    Usuario= models.CharField(max_length=30, db_column="LOC_Usua")
    Fecha= models.DateTimeField(db_column="LOC_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Direccion',)
        db_table = 'SISCBR_DLocal'

#Mantenimiento de Vehículo
class Vehiculo(models.Model):
    #Id= models.AutoField(db_column="VEH_Id", primary_key=True, unique=True, null=False)
    Cliente = models.ForeignKey(Cliente, db_column="CLI_Id")
    Modelo = models.CharField(db_column="VEH_Modelo", max_length=20)
    Marca = models.CharField(db_column="VEH_Marca", max_length=20)
    Color = models.CharField(db_column="VEH_Color", max_length=20)
    Anio = models.IntegerField(db_column="VEH_Anio", verbose_name="Año")
    Chofer = models.CharField(db_column="VEH_Chofer", max_length=45)
    Ruta = models.CharField(db_column="VEH_Ruta", max_length=45)
    Avaluo = models.DecimalField(db_column="VEH_Avaluo", max_digits=18, decimal_places=2, default=0.0)
    Capacidad = models.DecimalField(db_column="VEH_Capa", max_digits=10, decimal_places=2, default=0.0)
    Tipo = models.CharField(db_column="VEH_Tipo", max_length=45)
    Estado = models.BooleanField(db_column="VEH_Estado", default=True)
    Usuario = models.CharField(max_length=30, db_column="VEH_Usua")
    Fecha = models.DateTimeField(db_column="VEH_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Modelo

    class Meta:
        ordering = ('Anio',)
        db_table = 'SISCBR_MVehiculo'

#Tipo de Cobros
class Tipo_Cobro(models.Model):
    #Id= models.AutoField(db_column="TCO_Id", primary_key=True, unique=True, null=False)
    Descripcion = models.CharField(db_column="TCO_Desc", max_length=45, verbose_name="Descripción")
    Titulo = models.CharField(db_column="TCO_Titulo", max_length=90, verbose_name="Título")
    Subtitulo = models.CharField(db_column="TCO_Subtitulo", max_length=90, verbose_name="Subtítulo")
    Nombres = models.CharField(db_column="TCO_Nombres", max_length=90)
    Cargos = models.CharField(db_column="TCO_Cargos", max_length=90)
    Usuario = models.CharField(max_length=30, db_column="TCO_Usua")
    Fecha = models.DateTimeField(db_column="TCO_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Descripcion',)
        db_table = 'SISCBR_MTipoCobros'

#Cobro de Predios
class Cobro_Predios(models.Model):
    Anio=models.IntegerField(verbose_name="Año", db_column="COB_Anio", max_length=11, primary_key=True, null=False,
                             unique=True)
    Enero= models.DecimalField(db_column="COB_Ener", max_digits=10, decimal_places=2, default=0.0)
    Febrero= models.DecimalField(db_column="COB_Febr", max_digits=10, decimal_places=2, default=0.0)
    Marzo= models.DecimalField(db_column="COB_Marz", max_digits=10, decimal_places=2, default=0.0)
    Abril= models.DecimalField(db_column="COB_Abri", max_digits=10, decimal_places=2, default=0.0)
    Mayo= models.DecimalField(db_column="COB_Mayo", max_digits=10, decimal_places=2, default=0.0)
    Junio= models.DecimalField(db_column="COB_Juni", max_digits=10, decimal_places=2, default=0.0)
    Julio= models.DecimalField(db_column="COB_Juli", max_digits=10, decimal_places=2, default=0.0)
    Agosto= models.DecimalField(db_column="COB_Agos", max_digits=10, decimal_places=2, default=0.0)
    Septiembre= models.DecimalField(db_column="COB_Sept", max_digits=10, decimal_places=2, default=0.0)
    Octubre= models.DecimalField(db_column="COB_Octu", max_digits=10, decimal_places=2, default=0.0)
    Noviembre= models.DecimalField(db_column="COB_Novi", max_digits=10, decimal_places=2, default=0.0)
    Diciembre= models.DecimalField(db_column="COB_Dici", max_digits=10, decimal_places=2, default=0.0)
    Usuario= models.CharField(max_length=30,db_column="COB_Usua")
    Fecha= models.DateTimeField(db_column="COB_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Anio

    class Meta:
        ordering= ('Anio',)
        db_table= 'SISCBR_VCobPredios'

#Predios
class Predio(models.Model):
    #Id= models.AutoField(db_column="PDI_Id", primary_key=True, unique=True, null=False)
    Cliente=  models.ForeignKey(Cliente,db_column="CLI_Id")
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Catastro= models.CharField(db_column="PDI_Cata", max_length=20)
    Direccion= models.CharField(db_column="PDI_Direc", max_length=100, verbose_name="Dirección")

siscobros/siscobros/apps/main/forms.py
from django.forms import ModelForm
from .models import *

class T_CostoVarioForm(ModelForm):
    class Meta:
        model = Trans_Costo_Vario
        exclude = ['Estado','Fecha','Usuario']

siscobros/siscobros/templates/main/mantenimientos/Aseguradora.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Siscobros - Aseguradora {% endblock %}
{% block section %}
    <section class="ink-grid">
        <div class="container box">
            <h1 class="content-center">Aseguradoras</h1>
             <div id="grid"></div>
        </div>
        <script>

          $(document).ready(function () {
              var datasourse = new kendo.data.DataSource({
                  batch: true,
                  transport: {
                                   read: {
                                       url: "/aseguradora/read/",
                                       datatype: "json"
                                   },
                                   create: {
                                        url: "/aseguradora/add/",
                                        type: "POST",
                                        data: function(options){
                                               return {'Descripcion': options.models[0].Descripcion};
                                        }
                                   },
                                   update: {
                                       url: function(options){
                                            return "/aseguradora/edit/" + options.models[0].id;
                                       },
                                       data: function(options){
                                           return {'Descripcion': options.models[0].Descripcion};
                                       },
                                       type :"POST"

                                   },
                                   destroy: {
                                       url: function(options){
                                            return "/aseguradora/del/" + options.models[0].id;
                                       },
                                       type :"POST"
                                   }
                           },
                    schema: {
                                model: {
                                    id: "id",
                                       fields:{
                                            id: { editable:false, nullable: true ,type:"number" },
                                            Descripcion: { type: "string" }
                                       }
                                }

                           },
                           pageSize: 7
              });
              $("#grid").kendoGrid(
                      {
                       filterable: {
                            extra: false,
                            operators: {
                                string: {
                                    startswith: "Empieza con",
                                    eq: "Es igual a",
                                    neq: "No es igual a"
                                }
                            }
                        },
                        navigatable: true,
                        pageable: {
                            refresh: true,
                            pageSizes: true,
                            messages: {
                                    itemsPerPage : "Items por página"
                            }
                        },
                        height: 430,
                        toolbar: [{
                                name: "create",
                                text: "Nuevo"
                            }],
                          dataSource: datasourse,
                          columns: [
                              { field:"id", title:"Id", width: 120, filterable: false},
                              {
                                  field:"Descripcion",
                                  filterable: {
                                      ui: function(element){
                                              element.kendoAutoComplete({
                                                    dataSource: datasourse,
                                                    dataTextField: "Descripcion",
                                                    suggest: true
                                            });
                                      }
                                  },
                                   title:"Descripción"
                              },
                              {command: [
                                  {
                                   name: "edit",
                                   text: {
                                       edit: "Editar", cancel: "Cancelar", update: "Guardar"
                                   }
                                 },
                                  {name:"destroy", text: "Borrar"}
                              ], title: "Acciones", width: 200}
                       ],

                       batch: true,
                       editable: {
                               mode:"popup",
                               confirmation: "¿Está usted seguro de borrar este registro?",
                               window:{
                                    title: "Edición"
                               }

                       },
                       scrollable: true,
                       sortable: {
                           mode: "multiple"
                       },
                       save: function(){this.dataSource.read();this.refresh();},
                       cancel: function(){this.dataSource.read();}
                      });
          });
      </script>
    </section>
{% endblock %}

siscobros/siscobros/templates/main/mantenimientos/Ciudadela3.html
{% extends 'index.html'%}
{% load staticfiles %}
{% block title %} Siscobros - Ciudadela {% endblock %}
{% block body %}
  <section class="ink-grid">
        <div class="container box">
        	<h1 class="content-center">Ciudadelas</h1>

			<div class="ink-form">
				<div class="control-group">
					<div class="control append-button">

					<span class="control"><input type="text" id="txtCiu" placeholder="Ingrese texto a buscar"></span>
					<button class="ink-button red"><i class="icon-search"> </i> Buscar</button>
					</div>
					</div>
					</div>
			<button class="ink-button orange" href="#" id="bModal"> <i class="icon-plus-sign"> </i> </button>
           <div id="contenido">
               <table class="ink-table bordered hover alternating">
                    <thead>
                        <tr>
                           <th class="content-center">
                            Código
                           </th>
                           <th class="content-center">
                              Descripción
                           </th>
                           <th class="content-center" colspan="2">
                            Acciones
                           </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="1"> </td>
                        </tr>
                    </tfoot>
                    <tbody>
                     {% for ciu in ciudadela %}
                        <tr>
                            <td class="content-center">
                                {{ ciu.id }}
                            </td>
                            <td class="content-center">{{ ciu.Descripcion }}</td>
                            <td class="content-center"> <a href="#" class="ink-button" id="vModal"> <i class="icon-edit "> </i> Editar</a> </td>
                            <td class="content-center"> <a href="#" class="ink-button"><i class="icon-trash"> </i> Eliminar</a> </td>
                        </tr>
                     {% endfor %}
                    </tbody>
                </table>
                {% if ciudadela %}
                    <nav class="ink-navigation">
                        <ul class="pagination rounded shadowed red">
                            {% if ciudadela.has_previus %}
                                 <li class="previous"><a href="/ciudadela/pag/{{ciudadela.previus_page_number}}/"><i class="icon-chevron-left"> </i></a></li>
                            {% else %}
                                <li class="previous"><a href="#"><i class="icon-chevron-left"> </i></a></li>
                            {% endif %}
                            {% if ciudadela.has_next %}
                                <li class="next"><a href="/ciudadela/pag/{{ciudadela.next_page_number}}/"><i class="icon-chevron-right"> </i></a></li>
                            {% else %}
                                <li class="next"><a href="#"><i class="icon-chevron-right"> </i></a></li>
                            {% endif %}
                       </ul>
                    </nav>
                {% endif %}


           </div>

          </div>
      <script>


             //  $("#contenido").load("http://localhost:8000/Ciudadela/pag/1/Ciudadela.html"); //con esto en consola me recarga solo el div :D

          <!--Validar el doble envio de datos al refrescar -->
               var statSend = false;
                function checkSubmit() {
                    if (!statSend) {
                        statSend = true;
                        return true;
                    } else {
                        alert("El formulario ya se esta enviando...");
                        return false;
                    }
                }


      </script>
         <!--
         	Ventana modal nuevo
         -->
        <div class="ink-shade fade">
       <div id="nuevo" class="ink-modal" data-trigger="#bModal" data-width="910px" data-height="350px">
        <div class="modal-header">
            <button class="modal-close ink-dismiss"> </button>
            <h1> <i class="icon-plus-sign"></i> Nueva Ciudadela</h1>
        </div>
        <div class="modal-body" id="modalContent">
           <div class="box">

        	<form class="vspace ink-form" action="/ciudadela/add/" method="post" role="form" onsubmit="return checkSubmit();">
                {% csrf_token %}
			   <div class="control-group required column-group gutters">
                            <label for="txtDescripcion" class="large-20 content-right">Descripción </label>
                            <div class="control large-80">
                                <input type="text" id="txtDescripcion" name="txtDescripcion">
                            </div>
                </div>

                <div class="control-group modal-footer">
                    <div class="push-right">
                        <button id="guardar" class="ink-button blue info large" type="submit"><i class="icon-save"> </i> Guardar </button>
                        <button id="reset" class="ink-button red caution ink-dismiss large" > <i class="icon-remove-circle"> </i> Cancelar </button>
                    </div>
                </div>
			</form>
        </div>
    </div>
</div>
</div>
		<script>
            $("guardar").on('click',guardar);
            function guardar(){
                $("#contenido").load("http://localhost:8000/Ciudadela/ciudadela2.html"); //con esto en consola me recarga solo el div :D
            }
            $("#reset").on('click', borrar);
            function borrar(){
                $("#txtDescripcion").val('');
            }
		    var modal = new Ink.UI.Modal( '#nuevo' );
		    var modal = new Ink.UI.Modal('#editar');
		    /*Ink.requireModules( ['Ink.UI.Modal_1'], function(Modal){
		        new Modal( '#nuevo' );
		    });*/
//		    $(function() {
//		    	$('#id_Fecha').datepicker({
//		                 dateFormat: 'dd/mm/yy',
//		                 onSelect: function(datetext){
//		                    var d = new Date(); // for now
//		                    datetext=datetext+" "+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();
//		                    $('#id_Fecha').val(datetext);
//		                 },
//		             });
//		     });
		    $(function() {
		    	$('#Id_Fecha').datepicker({
		                 dateFormat: 'dd/mm/yy',
		                 onSelect: function(datetext){
		                    var d = new Date(); // for now
		                    datetext=datetext+" "+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();
		                    $('#id_Fecha').val(datetext);
		                 },
		             });
		     });

            $(function() {
                  $("#txtCiu").autocomplete({
                    source: "/autocompleteCiu/"

                  });
                });
		</script>
        </section>





  <!--<section class="ink-grid">-->
        <!--<div class="container box">-->
        	<!--<h1 class="content-center">Ciudadelas</h1>-->
        	<!--<form class="ink-form"  action="/registraCiudadela/" method="post" role="form">-->
                <!--{% csrf_token %}-->
			   <!--<div class="control-group required column-group gutters">-->
                            <!--<label class="large-20 content-right">Descripción </label>-->
                            <!--<div class="control large-60">-->
                                <!--<input type="text" id="txtDescripcion" name="txtDescripcion">-->
                            <!--</div>                            -->
                <!--</div>	-->
                <!--&lt;!&ndash;<div class="control-group required column-group gutters">&ndash;&gt;-->
                            <!--&lt;!&ndash;<label  class="large-20 content-right">Fecha de Emisión</label>&ndash;&gt;-->
                            <!--&lt;!&ndash;<div class="control large-30">&ndash;&gt;-->
                                <!--&lt;!&ndash;<input type="text" id="txtFecha" name="txtFecha">&ndash;&gt;-->
                            <!--&lt;!&ndash;</div>&ndash;&gt;-->
               <!--&lt;!&ndash;</div>&ndash;&gt;-->
               <!--<div class="control-group content-center">-->
                      <!--<button class="ink-button blue" type="submit"> <i class="icon-save icon-large"> </i> Guardar</button>-->
                      <!--&lt;!&ndash;<button class="ink-button red"> <i class="icon-remove-sign icon-large"> </i> Cancelar</button>	&ndash;&gt;-->
               <!--</div>-->
               					 <!---->
	        <!--</form>	-->
			<!---->
		  <!---->
        <!--</div>-->

       <!--<script>-->

           <!--$(function() {-->
                                <!--$('#txtFecha').datepicker({-->
                                    <!--dateFormat: 'dd/mm/yy',-->
                                    <!--onSelect: function(datetext){-->
                                        <!--var d = new Date(); // for now-->
                                        <!--datetext=datetext+" "+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();-->
                                        <!--$('#txtFecha').val(datetext);-->
                                    <!--},-->
                                <!--});-->
                                <!--});-->
           <!--//var modal = new Ink.UI.Modal('#editar');-->
           <!--Ink.requireModules( ['Ink.Dom.Selector_1','Ink.UI.Modal_1'], function( Selector, Modal ){-->
                 <!--var modalElement = Ink.s('#{{ciu.id}}');-->
                 <!--var modalObj = new Modal( modalElement );-->
             <!--});-->
       <!--</script>-->
        <!--</section>-->
    <!--<section class="ink-grid">-->
    <!--<div class="container box">-->
         <!--<h1 class="content-center">Ciudadelas</h1>-->

          <!--<table class="ink-table bordered hover alternating">-->
          	<!--<thead>-->
          		<!--<tr>-->
          		   <!--<th class="content-center">-->
          		   	<!--Código-->
          		   <!--</th>-->
          		   <!--<th class="content-center">-->
          		   	  <!--Descripción-->
          		   <!--</th>-->
          		   <!--<th class="content-center" colspan="3">-->
          		   	<!--Acciones-->
          		   <!--</th>-->
          		<!--</tr>-->
          	<!--</thead>-->
            <!--<tfoot>-->
            	<!--<tr>-->
            		<!--<td colspan="2"> </td>-->
            	<!--</tr>-->
            <!--</tfoot>-->
            <!--<tbody>-->
		<!--{% for ciu in ciudadela %}-->
			<!--<tr>-->
            		<!--<td class="content-center">-->
            			<!--{{ ciu.id }}-->
            		<!--</td>-->
            		<!--<td class="content-center">{{ ciu.Descripcion }}</td>-->
            		<!--<td class="content-center"> <a href="" class="ink-button" id="{{ciu.id}}"> <i class="icon-edit "> </i> Editar "{{ciu.id|length}}"</a> </td>-->
            		<!--<td class="content-center"> <a href="/EliminarCiudadela/{{ ciu.id }}" class="ink-button"><i class="icon-trash"> </i> Eliminar</a> </td>-->
            	<!--</tr>-->
              <!--<div class="ink-shade fade">-->
       <!--<div id="{{ciu.id}}" class="ink-modal" data-trigger="#vModal" data-width="910px" data-height="440px">-->
        <!--<div class="modal-header">-->
            <!--<button class="modal-close ink-dismiss"> </button>-->
            <!--<h1>Editar Ciudadela</h1>-->
        <!--</div>-->
        <!--<div class="modal-body" id="modalContent">-->
           <!--<div class="box">-->

        	<!--<div class="vspace ink-form">-->
			   <!--<div class="control-group required column-group gutters">-->
                            <!--<label for="email" class="large-20 content-right">Descripción </label>-->
                            <!--<div class="control large-80">-->
                                <!--<input type="text" id="Descripcion">-->
                            <!--</div>-->
                <!--</div>-->
                <!--<div class="control-group required column-group gutters">-->
                            <!--<label for="email" class="large-20 content-left">Fecha de Emisión</label>-->
                            <!--<div class="control large-30">-->
                                <!--<input type="text" id="Id_Fecha">-->
                            <!--</div>-->
               <!--</div>-->
			<!--</div>-->
        <!--</div>-->
        <!--<div class="vspace modal-footer">-->
            <!--<div class="push-right">-->
                <!--<button class="ink-button blue info large"><i class="icon-save"> </i> Guardar </button>-->
                <!--<button class="ink-button red caution ink-dismiss large"> <i class="icon-remove-circle"> </i> Cancelar </button>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</div>-->
<!--</div>-->
		<!--{% endfor %}-->
            <!--</tbody>-->
          <!--</table>-->
           <!--<nav class="ink-navigation">-->
				    <!--<ul class="pagination rounded shadowed red">-->
					    <!--<li class="previous"><a href="#"><i class="icon-chevron-left"> </i></a></li>-->
					    <!--<li class="next"><a href="#"><i class="icon-chevron-right"> </i></a></li>-->
				    <!--</ul>-->
			  <!--</nav>-->
    <!--</div>-->
     <!--</section>-->

{% endblock %}