siscobros/siscobros/apps/main/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('siscobros.apps.main.views',
                       url(r'^index/', 'main_view', name="vista_principal"),
                       url(r'^ciudadela/$','CiudadelaView'),
                       url(r'^ciudadela/read/$', 'serializaCiudadela', name="ConsumeCiudadela"),
                       url(r'^ciudadela/add/$','InsertCiudadela',name='RegistraCiudadela'),
                       url(r'^ciudadela/edit/(\d+)$','UpdateCiudadela'),
                       url(r'^ciudadela/del/(\d+)$','EliminaCiudadela'),
                       url(r'^costovario/$','TransCostoVario', name='TransCostoVario'),
                       url(r'^costovario/cbo/$','ComboTipoAjax',name="ComboTipo"),
                       url(r'^costovario/read/$','serializaTrans', name='ConsumeTrans'),
                       url(r'^aseguradora/$','AseguradoraView'),
                       url(r'^aseguradora/read/$','serializaAseguradora'),
                       url(r'^aseguradora/add/$','InsertAseguradora'),
                       url(r'^aseguradora/edit/(\d+)$','UpdateAseguradora'),
                       url(r'^aseguradora/del/(\d+)$','EliminaAseguradora'),
                       url(r'^reportes/costovario/$','rptcostoview'),
                       url(r'^reportes/costovario/file/$','reportecosto'),
                       )

siscobros/siscobros/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'siscobros.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('siscobros.apps.main.urls')),
    url(r'^$', 'django.contrib.auth.views.login',{ 'template_name': 'main/login.html'}, name="login"),
    url(r'^logout/', 'django.contrib.auth.views.logout_then_login', name="logout"),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

siscobros/siscobros/apps/main/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
# Create your models here. http://www.tangowithdjango.com/book
#Mantenimiento de Aseguradora v
class Aseguradora(models.Model):
    #Id= models.AutoField(db_column="ASE_Id", primary_key=True, unique=True, null=False)
    Descripcion= models.CharField(db_column="ASE_Desc", max_length=45, verbose_name="Descripción")
    Usuario= models.CharField(max_length=30, db_column="ASE_Usua")
    Fecha= models.DateTimeField(db_column="ASE_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Descripcion',)
        db_table = 'SISCBR_MAseguradora'

#Mantenimiento de Bombero v
class Bombero(models.Model):
    #Id= models.AutoField(db_column="PER_Id", primary_key=True, unique=True, null=False)
    Ruc = models.CharField(db_column="BOM_Ruc", max_length=15, primary_key=True, null=False, unique=True)
    Nombre = models.CharField(db_column="BOM_Nombre", max_length=45)
    Logotipo = models.CharField(db_column="BOM_Logotipo", max_length=45)
    Direccion = models.CharField(db_column="BOM_Direccion", max_length= 45, verbose_name="Dirección")
    Telefono = models.CharField(db_column="BOM_Telefono", max_length= 45, verbose_name="Teléfono")
    Fax = models.CharField(db_column="BOM_Fax", max_length=20)
    Mail = models.EmailField(db_column="BOM_Mail", max_length=45, verbose_name="Email")
    Web = models.URLField(db_column="BOM_Web")
    Slogan = models.CharField(db_column= "BOM_Slogan", max_length=45)
    RUC_Comandante = models.CharField(db_column="BOM_Ruc_Comandante", max_length=15, null=False, unique=True,
                                            verbose_name="Ruc Comandante")
    Comandante = models.CharField(db_column="BOM_Comandante", max_length=45)
    Usuario = models.CharField(max_length=30, db_column= "BOM_Usua")
    Fecha = models.DateTimeField(db_column= "BOM_Fech", default=datetime.today(), verbose_name="Fecha de Creación")
    Cost_Titulo= models.DecimalField(db_column="BOM_Cost_Titulo", max_digits=10, decimal_places=2,
                                     verbose_name="Costo Título")
    Tasa_Predio = models.DecimalField(db_column="BOM_Tasa_Predio", max_digits=10, decimal_places=2,
                                     verbose_name="Tasa Predio")
    Tasa_Certificado = models.DecimalField(db_column="BOM_Tasa_Certificado", max_digits=10, decimal_places=2,
                                     verbose_name="Tasa Certificado")

    def __unicode__(self):
        return str(self.Nombre)

    class Meta:
        ordering = ('Nombre',)
        db_table = 'SISCBR_Bombero'

#Mantenimiento de Ciudadela
class Ciudadela(models.Model):
    #Id= models.AutoField(db_column="CIU_Id", primary_key=True, unique=True, null=False)
    Descripcion = models.CharField(db_column="CIU_Desc", max_length=45, verbose_name="Descripción")
    Usuario = models.CharField(max_length=30, db_column="CIU_Usua")
    Fecha= models.DateTimeField(db_column="CIU_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering= ('Descripcion',)
        db_table= 'SISCBR_MCiudadela'

#Mantenimiento de Cliente
class Cliente(models.Model):
    #Id= models.AutoField(db_column="CLI_Id", primary_key=True, unique=True, null=False)
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Cedula= models.CharField(db_column="CLI_Cedu", max_length=13, verbose_name="Cédula")
    Apellido= models.CharField(db_column="CLI_Apel", max_length=45)
    Nombre= models.CharField(db_column="CLI_Nomb", max_length=45)
    Direccion= models.CharField(db_column="CLI_Dire", max_length=45, verbose_name="Dirección")
    Telefono= models.CharField(db_column="CLI_Fono", max_length=20, verbose_name="Teléfono")
    Email= models.EmailField(db_column="CLI_Mail", max_length=45)
    Usuario= models.CharField(max_length=30, db_column="CLI_Usua")
    Fecha= models.DateTimeField(db_column="CLI_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return '%s %s'%(self.Nombre, self.Apellido)

    class Meta:
        ordering = ('Apellido',)
        db_table = 'SISCBR_MCliente'

#Local
class Local(models.Model):
    #Id= models.AutoField(db_column="LOC_Id", primary_key=True, unique=True, null=False)
    Cliente= models.ForeignKey(Cliente, db_column="CLI_Id")
    Aseguradora= models.ForeignKey(Aseguradora, db_column="ASE_Id")
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Descripcion= models.CharField(db_column="LOC_Desc", max_length=45, verbose_name="Descripción")
    Ruc= models.CharField(db_column="LOC_Ruc", max_length=13)
    Direccion= models.CharField(db_column="LOC_Direc", max_length=45, verbose_name="Dirección")
    Catastro= models.CharField(db_column="LOC_Cata", max_length=20)
    Telefono= models.CharField(db_column="LOC_Fono", max_length=20, verbose_name="Teléfono")
    Avaluo= models.DecimalField(db_column="LOC_Avaluo", max_digits=18, decimal_places=2, default=0.0)
    Poliza= models.CharField(db_column="LOC_NPol", max_length=20, verbose_name="N° de Póliza")
    Estado = models.BooleanField(db_column="LOC_Est", default=True)
    Usuario= models.CharField(max_length=30, db_column="LOC_Usua")
    Fecha= models.DateTimeField(db_column="LOC_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Direccion',)
        db_table = 'SISCBR_DLocal'

#Mantenimiento de Vehículo
class Vehiculo(models.Model):
    #Id= models.AutoField(db_column="VEH_Id", primary_key=True, unique=True, null=False)
    Cliente = models.ForeignKey(Cliente, db_column="CLI_Id")
    Modelo = models.CharField(db_column="VEH_Modelo", max_length=20)
    Marca = models.CharField(db_column="VEH_Marca", max_length=20)
    Color = models.CharField(db_column="VEH_Color", max_length=20)
    Anio = models.IntegerField(db_column="VEH_Anio", verbose_name="Año")
    Chofer = models.CharField(db_column="VEH_Chofer", max_length=45)
    Ruta = models.CharField(db_column="VEH_Ruta", max_length=45)
    Avaluo = models.DecimalField(db_column="VEH_Avaluo", max_digits=18, decimal_places=2, default=0.0)
    Capacidad = models.DecimalField(db_column="VEH_Capa", max_digits=10, decimal_places=2, default=0.0)
    Tipo = models.CharField(db_column="VEH_Tipo", max_length=45)
    Estado = models.BooleanField(db_column="VEH_Estado", default=True)
    Usuario = models.CharField(max_length=30, db_column="VEH_Usua")
    Fecha = models.DateTimeField(db_column="VEH_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Modelo

    class Meta:
        ordering = ('Anio',)
        db_table = 'SISCBR_MVehiculo'

#Tipo de Cobros
class Tipo_Cobro(models.Model):
    #Id= models.AutoField(db_column="TCO_Id", primary_key=True, unique=True, null=False)
    Descripcion = models.CharField(db_column="TCO_Desc", max_length=45, verbose_name="Descripción")
    Titulo = models.CharField(db_column="TCO_Titulo", max_length=90, verbose_name="Título")
    Subtitulo = models.CharField(db_column="TCO_Subtitulo", max_length=90, verbose_name="Subtítulo")
    Nombres = models.CharField(db_column="TCO_Nombres", max_length=90)
    Cargos = models.CharField(db_column="TCO_Cargos", max_length=90)
    Usuario = models.CharField(max_length=30, db_column="TCO_Usua")
    Fecha = models.DateTimeField(db_column="TCO_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Descripcion

    class Meta:
        ordering = ('Descripcion',)
        db_table = 'SISCBR_MTipoCobros'

#Cobro de Predios
class Cobro_Predios(models.Model):
    Anio=models.IntegerField(verbose_name="Año", db_column="COB_Anio", max_length=11, primary_key=True, null=False,
                             unique=True)
    Enero= models.DecimalField(db_column="COB_Ener", max_digits=10, decimal_places=2, default=0.0)
    Febrero= models.DecimalField(db_column="COB_Febr", max_digits=10, decimal_places=2, default=0.0)
    Marzo= models.DecimalField(db_column="COB_Marz", max_digits=10, decimal_places=2, default=0.0)
    Abril= models.DecimalField(db_column="COB_Abri", max_digits=10, decimal_places=2, default=0.0)
    Mayo= models.DecimalField(db_column="COB_Mayo", max_digits=10, decimal_places=2, default=0.0)
    Junio= models.DecimalField(db_column="COB_Juni", max_digits=10, decimal_places=2, default=0.0)
    Julio= models.DecimalField(db_column="COB_Juli", max_digits=10, decimal_places=2, default=0.0)
    Agosto= models.DecimalField(db_column="COB_Agos", max_digits=10, decimal_places=2, default=0.0)
    Septiembre= models.DecimalField(db_column="COB_Sept", max_digits=10, decimal_places=2, default=0.0)
    Octubre= models.DecimalField(db_column="COB_Octu", max_digits=10, decimal_places=2, default=0.0)
    Noviembre= models.DecimalField(db_column="COB_Novi", max_digits=10, decimal_places=2, default=0.0)
    Diciembre= models.DecimalField(db_column="COB_Dici", max_digits=10, decimal_places=2, default=0.0)
    Usuario= models.CharField(max_length=30,db_column="COB_Usua")
    Fecha= models.DateTimeField(db_column="COB_Fech", default=datetime.today(), verbose_name="Fecha de Creación")

    def __unicode__(self):
        return self.Anio

    class Meta:
        ordering= ('Anio',)
        db_table= 'SISCBR_VCobPredios'

#Predios
class Predio(models.Model):
    #Id= models.AutoField(db_column="PDI_Id", primary_key=True, unique=True, null=False)
    Cliente=  models.ForeignKey(Cliente,db_column="CLI_Id")
    Ciudadela= models.ForeignKey(Ciudadela, db_column="CIU_Id")
    Catastro= models.CharField(db_column="PDI_Cata", max_length=20)
    Direccion= models.CharField(db_column="PDI_Direc", max_length=100, verbose_name="Dirección")

siscobros/siscobros/apps/main/forms.py
from django.forms import ModelForm
from .models import *

class T_CostoVarioForm(ModelForm):
    class Meta:
        model = Trans_Costo_Vario
        exclude = ['Estado','Fecha','Usuario']

siscobros/siscobros/templates/main/demo.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block title %}
        Prueba de funcionamiento de formularios
{% endblock %}
{% block body %}
     <!--#EDEDED-->
        <div class="ink-grid">
                {% block header %}
                    <header>
                        <h1>Sistema de Cobros v1.0 <small>Cuerpo de Bomberos</small> </h1>
                        <nav class="ink-navigation vspace">
                            <ul class = "menu horizontal red rounded shadowed">
                                <li><a href="#"><i class="icon-sitemap"> </i>Mantenimiento <i class="icon-caret-down"> </i></a>
                                <ul class="submenu">
                                   <li><a href="#"> Contribuyentes  </a></li>
                                   <li><a href="#"> Ciudadela </a></li>
                                   <li><a href="#"> Aseguradoras </a></li>
                                   <li><a href="#"> Vehículos </a></li>
                                   <li><a href="#"> Locales </a></li>
                                </ul>
                            </li>
                            <li><a href="#"><i class="icon-exchange"> </i>Transacción <i class="icon-caret-down"> </i></a>
                                <ul class="submenu">
                                    <li><a href="#"><i class="icon-time"> </i>Deudas</a></li>
                                    <li><a href="#"><i class="icon-money"> </i>Cobros</a></li>
                                </ul>
                                </li>
                            <li><a href="#"><i class="icon-search"> </i>Inspección</a></li>
                            <li><a href="#"><i class="icon-bar-chart"> </i>Reportería</a></li>
                            <li><a href="#"><i class="icon-wrench"> </i>Parámetros <i class="icon-caret-down"></i></a>
                                <ul class="submenu">
                                    <li><a href="#"> Recargas </a></li>
                                    <li><a href="#">Organización </a></li>
                                </ul>
                            </li>
                            <li class="push-right">
                              <a href="#"><i class="icon-user">  </i> Bienvenido {{usuario}}</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'logout'%}"><i class="icon-signout"> </i> Salir </a></li>
                                </ul>
                             </li>
                            </ul>
                        </nav>
                    </header>
                {% endblock %}
                {% block section %}
                <section class="container box">
                    <h1 class="content-center">Pagos</h1>
                    <form action="." id="form" method="POST" class="ink-form">
                        {% csrf_token %}
                        <div class="control-group required column-group gutters">
                                    <label for="email" class="large-20 content-right">Título </label>
                                    <div class="control large-30">
                                        {{ form.Titulo }}
                                    </div>
                                    <div class="control large-30">
                                        <input type="text" id="id_Numero">
                                        <p class="tip">Número</p>
                                    </div>
                        </div>
                        <div class="control-group required column-group gutters">
                                    <label for="email" class="large-20 content-right">Por </label>
                                    <div class="control large-20">
                                        {{ form.Valor }}
                                    </div>
                        </div>
                       <div class="control-group required column-group gutters">
                                    <label for="email" class="large-20 content-right">Cliente </label>
                                    <div class="control large-60">
                                        {{ form.Ciente }}
                                    </div>
                        </div>
                        <div class="control-group required column-group gutters">
                                    <label for="Fecha" class="large-20 content-right">Tipo</label>
                                    <div class="control large-30">
                                        {{ form.Tipo_Costo }} # cual es el id del combo
                                    </div>
                       </div>
                        <div class="control-group required column-group gutters">
                                    <label for="Fecha" class="large-20 content-right">Concepto</label>
                                    <div class="control large-70">
                                        {{ form.Observacion }}
                                    </div>
                       </div>
                       <div class="control-group required column-group gutters">
                                    <label for="Fecha" class="large-20 content-right">Cantidad</label>
                                    <div class="control large-60">
                                        <input type="text" id="id_Cantidad">
                                    </div>
                       </div>
                       <div class="control-group content-center">
                              <button class="ink-button blue"> <i class="icon-save icon-large"> </i> Guardar</button>
                              <a href="/index/"class="ink-button red"> <i class="icon-remove-sign"> </i> Cancelar </a>
                       </div>
                    </form>

                     <script>

                         $("#id_Tipo_Costo").on('click', capturatipo);
                         function capturatipo(){
                             //var texto = $("#id_Tipo_Costo option:selected").text();
                             var iden = $("#id_Tipo_Costo").val();
                             var tit = $("#id_Titulo").val();
                             $.ajax(
                                     {
                                         data: {'id': iden, 'tit':tit},
                                         datatype: 'json',
                                         url:'{% url "tipocostovario" %}',
                                         type: 'post',
                                         success: function(data){
                                         if(data==0)
                                         {
                                            alert("algo salio mal");
                                         }
                                         else{
                                             alert(data);
                                         }

                                        }
                                     }

                             );
                             console.log(iden,tit);
                         }
                          //con esto habilito el ckeditor
                         $("textarea").addClass("ckeditor");
                      </script>

               </section>
                {% endblock %}
                {% block footer %}
                    <footer>
                        <div class="ink-grid">
                               <p>Copyright&copy; 2014 Todos los derechos Reservados </p>
                        </div>
                    </footer>
                {% endblock %}
        </div>

{% endblock %}

siscobros/siscobros/templates/main/login.html
{%load staticfiles%}<!DOCTYPE html><!--[if lt IE 7]><html lang="es" class="ie6 ielt8"><![endif]--><!--[if IE 7]><html lang="es" class="ie7 ielt8"><![endif]--><!--[if IE 8]><html lang="es" class="ie8"><![endif]--><!--[if(gte IE 9)|!(IE)]><!--><html lang="es"><!--<![endif]--><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>SisCobros-Login</title><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"><link rel="stylesheet" type="text/css" href="{% static 'css/ink-min.css' %}"/><link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}"/><!--[if IE 7]><link rel="stylesheet" href=" {% static 'css/ink-ie7-min.css' %} type="text/css" media="screen" title="no title" charset="utf-8<!--<![endif]&ndash;&gt;--></head><body><div class="container">{%if not user.is_authenticated%}<section id="content"><form action="../" method="POST">{%csrf_token%}<h1>Iniciar Sesión</h1><div><input type="text" placeholder="Nombre de Usuario" required="" id="username" name="username"/></div><div><input type="password" placeholder="Contraseña" required="" id="password" name="password"/></div><div><button type="submit" class="ink-button red"><i class="icon-signin"></i>Entrar</button></div></form>{%else%}<meta http-equiv="refresh" content="0; url=/index/"/>{%endif%}</section>{%if form.errors%}<div class="ink-alert basic error"><button class="ink-dismiss">&times;</button><p><b>Error:</b>Usuario o Contraseña Incorrectos</p></div>{%endif%}</div></body></html>

siscobros/siscobros/templates/main/test.html
  <section class="container box">
                                <div id="tabs">
                                <ul>
                                    <li><a href="#fragment-1" id="tabConsulta">Consulta</a></li>
                                    <li><a href="#fragment-2" id="tabPagos">Pagos</a></li>
                                </ul>
                                <div id="fragment-1">
                                    <div class="ink-grid">
                                        <form class="ink-form" action="">
                                            <div class="container box">


                                                <div class="ink-form">
                                                    <div class="control-group">
                                                        <div class="control append-button">

                                                        <span class="control"><input type="text" id="name" placeholder="Ingrese texto a buscar"></span>
                                                        <button class="ink-button red"><i class="icon-search"> </i> Buscar</button>
                                                        </div>
                                                        </div>
                                                        </div>

                                              <table class="ink-table bordered hover alternating">
                                                <thead>
                                                    <tr>
                                                       <th class="content-center">
                                                        Código
                                                       </th>
                                                       <th class="content-center">
                                                          Descripción
                                                       </th>
                                                       <th class="content-center" colspan="3">
                                                        Acciones
                                                       </th>
                                                    </tr>
                                                </thead>
                                                <tfoot>
                                                    <tr>
                                                        <td colspan="1"> </td>
                                                    </tr>
                                                </tfoot>
                                                <tbody>
                                                    <tr>
                                                        <td class="content-center">
                                                            1
                                                        </td>
                                                        <td class="content-center">Santa Rosita</td>
                                                        <td class="content-center"><a href="" class="ink-button green"><i class="icon-ticket"> </i> Pagos</a></td>
                                                    </tr>
                                                        <tr>
                                                        <td class="content-center">
                                                            2
                                                        </td>
                                                        <td class="content-center">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. </td>
                                                        <td class="content-center"><a href="" class="ink-button green"><i class="icon-ticket"> </i> Pagos</a></td>
                                                    </tr>
                                                </tbody>
                                              </table>
                                               <nav class="ink-navigation">
                                                        <ul class="pagination rounded shadowed red">
                                                            <li class="previous"><a href="#"><i class="icon-chevron-left"> </i></a></li>
                                                            <li class="next"><a href="#"><i class="icon-chevron-right"> </i></a></li>
                                                        </ul>
                                                  </nav>
                                              </div>
                                        </form>
                                    </div>
                                </div>
                                <div id="fragment-2">
                                    <div class="ink-grid">
                                        <form action="" class="container box ink-form">
                                                <h1 class="content-center"> Pagos </h1>
                                                <p class="content-center tip"> Por favor rellene los campos marcados con *</p>
                                                <div class="control-group required column-group gutters">
                                                            <label for="email" class="large-20 content-right">Título </label>
                                                            <div class="control large-30">
                                                                <input type="text" id="id_Titulo">
                                                            </div>
                                                            <div class="control large-30">
                                                                <input type="text" id="id_Numero">
                                                                <p class="tip">Número</p>
                                                            </div>
                                                </div>
                                                <div class="control-group required column-group gutters">
                                                            <label for="email" class="large-20 content-right">Por </label>
                                                            <div class="control large-20">
                                                                <input type="text" id="id_Por">
                                                            </div>
                                                </div>
                                               <div class="control-group required column-group gutters">
                                                            <label for="email" class="large-20 content-right">Cliente </label>
                                                            <div class="control large-60">
                                                                <input type="text" id="id_Cliente">
                                                            </div>
                                                </div>
                                                <div class="control-group required column-group gutters">
                                                            <label for="Fecha" class="large-20 content-right">Tipo</label>
                                                            <div class="control large-30">
                                                                <select name="" id="id_Tirpo">
                                                                    <option>Escoja una de las opciones</option>
                                                                </select>
                                                            </div>
                                               </div>
                                                <div class="control-group required column-group gutters">
                                                            <label for="Fecha" class="large-20 content-right">Concepto</label>
                                                            <div class="control large-70">
                                                                <textarea  id="id_Concepto" class="ckeditor"> </textarea>
                                                            </div>
                                               </div>
                                               <div class="control-group required column-group gutters">
                                                            <label for="Fecha" class="large-20 content-right">Cantidad</label>
                                                            <div class="control large-60">
                                                                <input type="text" id="id_Cantidad">
                                                            </div>
                                               </div>
                                               <div class="control-group content-center">
                                                      <button class="ink-button blue"> <i class="icon-save icon-large"> </i> Guardar</button>
                                                      <button class="ink-button red"> <i class="icon-remove-sign icon-large"> </i> Cancelar</button>
                                               </div>
                                        </form>
                                    </div>
                                </div>
                              </div>
</section>